#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x9b,0x75,0xe8,0xf8,0x9a,0x14,
    0x01,0x04,0xcf,0xb4,0xe3,0xa3,0x9a,0x14,
    0x01,0x04,0xa9,0x3a,0x3d,0x47,0x9a,0x14,
};

static const uint8_t chainparams_seed_signet[] = {
};

static const uint8_t chainparams_seed_test[] = {
};

static const uint8_t chainparams_seed_testnet4[] = {
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
