description "GoldBrix Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env GOLDBRIXD_BIN="/usr/bin/goldbrixd"
env GOLDBRIXD_USER="goldbrix"
env GOLDBRIXD_GROUP="goldbrix"
env GOLDBRIXD_PIDDIR="/var/run/goldbrixd"
# upstart can't handle variables constructed with other variables
env GOLDBRIXD_PIDFILE="/var/run/goldbrixd/goldbrixd.pid"
env GOLDBRIXD_CONFIGFILE="/etc/goldbrix/goldbrix.conf"
env GOLDBRIXD_DATADIR="/var/lib/goldbrixd"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # goldbrixd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$GOLDBRIXD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run goldbrixd."
        echo "The setting must appear in $GOLDBRIXD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"GoldBrix Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$GOLDBRIXD_PIDDIR"
    chmod 0755 "$GOLDBRIXD_PIDDIR"
    chown $GOLDBRIXD_USER:$GOLDBRIXD_GROUP "$GOLDBRIXD_PIDDIR"
    chown $GOLDBRIXD_USER:$GOLDBRIXD_GROUP "$GOLDBRIXD_CONFIGFILE"
    chmod 0660 "$GOLDBRIXD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$GOLDBRIXD_PIDFILE" \
    --chuid $GOLDBRIXD_USER:$GOLDBRIXD_GROUP \
    --exec "$GOLDBRIXD_BIN" \
    -- \
    -pid="$GOLDBRIXD_PIDFILE" \
    -conf="$GOLDBRIXD_CONFIGFILE" \
    -datadir="$GOLDBRIXD_DATADIR" \
    -disablewallet \
    -daemon

